version: '3.4'

services:
  postgres:
    image: postgres
  
  redis:
    image: redis

  seq:
    image: datalust/seq 
    
  tracker.webapi:
    image: ${DOCKER_REGISTRY-}trackerwebapi
    build:
      context: .
      dockerfile: src/WebApi/Tracker.WebApi/Dockerfile
  
  #sqlserver:
  #  image: mysql
  
  # pgadmin:
  #   image: dpage/pgadmin4