version: '3.4'

networks:
  trackerwebapi-dev:
    driver: bridge

services:
  tracker.webapi:
    image: ${DOCKER_REGISTRY-}trackerwebapi
    build:
      context: .
      dockerfile: src/WebApi/Tracker.WebApi/Dockerfile
    container_name: trackerwebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=tracker_dev;Username=postgres;Password=
      - ConnectionStrings__RedisConnection=redis:6379
      - Serilog__Seq__Url=http://seq:5341
    ports:
      - "5001:443"
      - "5000:80"
    depends_on:
      - postgres
      #- sqlserver
      #- pgadmin
    networks:
      - trackerwebapi-dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - trackerwebapi-dev
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - redis
    ports:
      - "127.0.0.1:5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=trust
    networks:
      - trackerwebapi-dev
    ports:
      - "6379:6379"
    volumes: 
      - redis:/data

  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - trackerwebapi-dev
    ports:
      - 5341:80

volumes:
  seq:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local