version: "3.7"

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - tracker
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data

networks:
  tracker:
    name: tracker

volumes:
  postgres:
    driver: local