version: "3.7"

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - tracker
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - tracker
    ports:
      - "6379:6379"
    volumes: 
      - redis:/data

  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - tracker
    ports:
      - 5341:80

networks:
  tracker:
    name: tracker

volumes:
  seq:
    driver: local
  postgres:
    driver: local
  redis: 
    driver: local