@id = d6e9c7db-95a9-4ffd-bce5-2946bcff0fbc

###
# Get all employees
GET {{url}}/{{employye}}
Content-Type: application/json
# Authorization: Bearer {{accessToken}}
###

# Get all employees
GET {{url}}/{{employye}}/{{id}}
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

# string Name, string Sex, DateOnly Birthday, Guid RoleId
###
POST {{url}}/{{employye}}
Content-Type: application/json

{
  "name": "Test",
  "sex": "man",
  "birthday": "2023-01-01",
  "roleId": "a13154b7-1954-4c36-a6cb-365364410a86"
}

# string Name, DateOnly CreatedAt, DateOnly FinishedAt
###
PUT {{url}}/{{employye}}
Content-Type: application/json

{
  "id": "d6e9c7db-95a9-4ffd-bce5-2946bcff0fbc",
  "name": "Test30"
}

# string id - delete by id
###
DELETE {{url}}/{{employye}}/{{id}}
Content-Type: application/json
