@id = 03bef90d-2994-446b-8617-3cd5d369a488

###
# Get all employees
GET {{url}}/{{employye}}
Content-Type: application/json
# Authorization: Bearer {{accessToken}}
###

# Get all employees
GET {{url}}/{{employye}}/{{id}}
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

# string Name, string Sex, DateOnly Birthday, Guid RoleId
###
POST {{url}}/{{employye}}
Content-Type: application/json

{
  "name": "Test2",
  "sex": "man",
  "birthday": "2023-01-01",
  "roleId": "261775be-7696-436c-8d99-8a5d5c0a8c16"
}

# string Name, DateOnly CreatedAt, DateOnly FinishedAt
###
PUT {{url}}/{{employye}}
Content-Type: application/json

{
  "id": "d6e9c7db-95a9-4ffd-bce5-2946bcff0fbc",
  "name": "Test30"
}

# string id - delete by id
###
DELETE {{url}}/{{employye}}/{{id}}
Content-Type: application/json
