@url = http://localhost:5000/api/Project
@accessToken = test
@pageNumber=1
@pageSize=10

###
GET {{url}}
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

# string Name, DateOnly CreatedAt, DateOnly FinishedAt
###
POST {{url}}
Content-Type: application/json

{
  "createdAt": "2021-01-01",
  "employeeId": "e1a88f13-54f4-40bd-a622-cf5f329fe4ba",
  "finishedAt": "2023-01-01",
  "name": "Test"
}

# string Name, DateOnly CreatedAt, DateOnly FinishedAt
###
PUT {{url}}
Content-Type: application/json

{
  "id": "9ad46bce-7767-4325-bf13-0547722c4004",
  "createdAt": "2021-01-01",
  "finishedAt": "2023-01-01",
  "name": "Test30"
}

# string Name, DateOnly CreatedAt, DateOnly FinishedAt
###
# DELETE {{url}}/?Id=b5a09aa5-2176-4e3d-963b-5105f34f3ec3
DELETE {{url}}/9ad46bce-7767-4325-bf13-0547722c4004
Content-Type: application/json

# string ןג
###
# DELETE {{url}}/?Id=b5a09aa5-2176-4e3d-963b-5105f34f3ec3
GET {{url}}/5cc28a32-548b-4d5b-89f8-8321022f2e2f
Content-Type: application/json

# Guid EmployeeId, Guid ProjectId, DateOnly Start
###
GET {{url}}/ByTime?EmployeeId=d5a8ac92-6f7a-407e-a3b5-2089bf9a4dff&ProjectId=5cc28a32-548b-4d5b-89f8-8321022f2e2f&year=0&month=0&day=0&dayOfWeek=0
Content-Type: application/json

# Authorization: Bearer {{accessToken}}

###
# GET {{url}}/vacancies/skills?PageNumber={{{pageNumber}}}&PageSize={{pageSize}}&Skills=AspNet&Skills=English
# Content-Type: application/json
# Authorization: Bearer {{accessToken}}

# ###
# GET {{url}}/vacancies/salary?PageNumber={{{pageNumber}}}&PageSize={{pageSize}}&Salary=1000
# Content-Type: application/json
# Authorization: Bearer {{accessToken}}