# @url = http://localhost:5000/api/Roles
@id = de97f7c3-6f5b-4082-8204-775be4bddf86
# @pageNumber=1
# @pageSize=10

###
# GET {{url}}/all
GET {{url}}/{{roles}}
Content-Type: application/json

###
# GET {{url}}/id - get single by id
GET {{url}}/{{roles}}/{{id}}
Content-Type: application/json

# string name
###
POST {{url}}/{{roles}}
Content-Type: application/json

"User5"

# string name, string id
###
PUT {{url}}/{{roles}}
Content-Type: application/json

{
    "name": "User",
    "id": "{{id}}"
}

# id - delete Role
###
DELETE  {{url}}/{{roles}}/{{id}}
Content-Type: application/json


# # string Name, DateOnly CreatedAt, DateOnly FinishedAt
# ###
# PUT {{url}}/{{roles}}
# Content-Type: application/json

# {
#   "id": "9ad46bce-7767-4325-bf13-0547722c4004",
#   "createdAt": "2021-01-01",
#   "finishedAt": "2023-01-01",
#   "name": "Test30"
# }

# # string Name, DateOnly CreatedAt, DateOnly FinishedAt
# ###
# # DELETE {{url}}/{{roles}}/?Id=b5a09aa5-2176-4e3d-963b-5105f34f3ec3
# DELETE {{url}}/{{roles}}/9ad46bce-7767-4325-bf13-0547722c4004
# Content-Type: application/json

# # string ןג
# ###
# # DELETE {{url}}/{{roles}}/?Id=b5a09aa5-2176-4e3d-963b-5105f34f3ec3
# GET {{url}}/{{roles}}/5cc28a32-548b-4d5b-89f8-8321022f2e2f
# Content-Type: application/json

# # Guid EmployeeId, Guid ProjectId, DateOnly Start
# ###
# GET {{url}}/{{roles}}/ByTime?EmployeeId=d5a8ac92-6f7a-407e-a3b5-2089bf9a4dff&ProjectId=5cc28a32-548b-4d5b-89f8-8321022f2e2f&year=0&month=0&day=0&dayOfWeek=0
# Content-Type: application/json

# # Authorization: Bearer {{accessToken}}

# ###
# # GET {{url}}/vacancies/skills?PageNumber={{{pageNumber}}}&PageSize={{pageSize}}&Skills=AspNet&Skills=English
# # Content-Type: application/json
# # Authorization: Bearer {{accessToken}}

# # ###
# # GET {{url}}/vacancies/salary?PageNumber={{{pageNumber}}}&PageSize={{pageSize}}&Salary=1000
# # Content-Type: application/json
# # Authorization: Bearer {{accessToken}}