# @url = http://localhost:5000/api/Roles
@id = de97f7c3-6f5b-4082-8204-775be4bddf86
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImZlZjY4YmI5LTRkNmEtNDhiMy04YTM5LTdjOWMwMmY1Njc1MSIsInN1YiI6ImZlZjY4YmI5LTRkNmEtNDhiMy04YTM5LTdjOWMwMmY1Njc1MSIsImlhdCI6IjE2ODMzNTM2NDM5NzYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ0ZXN0MSIsIm5iZiI6MTY4MzM1MzY0MywiZXhwIjoxNjgzMzU3MjQzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJ0cmFja2VyLXN5c3RlbSJ9.69pQqJL_J-tNRReoATIzdbhbiOqYxTHUxhIurms6KXM 
# @pageNumber=1
# @pageSize=10

###
# GET {{url}}/all
GET {{url}}/{{roles}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# GET {{url}}/id - get single by id
GET {{url}}/{{roles}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

# string name
###
POST {{url}}/{{roles}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

"User5"

# string name, string id
###
PUT {{url}}/{{roles}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "User",
    "id": "{{id}}"
}

# id - delete Role
###
DELETE  {{url}}/{{roles}}/{{id}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}


# # string Name, DateOnly CreatedAt, DateOnly FinishedAt
# ###
# PUT {{url}}/{{roles}}
# Content-Type: application/json

# {
#   "id": "9ad46bce-7767-4325-bf13-0547722c4004",
#   "createdAt": "2021-01-01",
#   "finishedAt": "2023-01-01",
#   "name": "Test30"
# }

# # string Name, DateOnly CreatedAt, DateOnly FinishedAt
# ###
# # DELETE {{url}}/{{roles}}/?Id=b5a09aa5-2176-4e3d-963b-5105f34f3ec3
# DELETE {{url}}/{{roles}}/9ad46bce-7767-4325-bf13-0547722c4004
# Content-Type: application/json

# # string ןג
# ###
# # DELETE {{url}}/{{roles}}/?Id=b5a09aa5-2176-4e3d-963b-5105f34f3ec3
# GET {{url}}/{{roles}}/5cc28a32-548b-4d5b-89f8-8321022f2e2f
# Content-Type: application/json

# # Guid EmployeeId, Guid ProjectId, DateOnly Start
# ###
# GET {{url}}/{{roles}}/ByTime?EmployeeId=d5a8ac92-6f7a-407e-a3b5-2089bf9a4dff&ProjectId=5cc28a32-548b-4d5b-89f8-8321022f2e2f&year=0&month=0&day=0&dayOfWeek=0
# Content-Type: application/json

# # Authorization: Bearer {{accessToken}}

# ###
# # GET {{url}}/vacancies/skills?PageNumber={{{pageNumber}}}&PageSize={{pageSize}}&Skills=AspNet&Skills=English
# # Content-Type: application/json
# # Authorization: Bearer {{accessToken}}

# # ###
# # GET {{url}}/vacancies/salary?PageNumber={{{pageNumber}}}&PageSize={{pageSize}}&Salary=1000
# # Content-Type: application/json
# # Authorization: Bearer {{accessToken}}