# @url = http://localhost:5000/api/login
@name = test1
@password = 12345
@role = User


# string name, string password
###
POST {{url}}/{{Security}}/{{login}}
Content-Type: application/json

{
    "name": "{{name}}",
    "password": "{{password}}"
}
# string name, string password
###
POST {{url}}/{{Security}}/{{register}}
Content-Type: application/json

{
    "name": "{{name}}",
    "password": "{{password}}"
}
